#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaMOTDWatchVideoWidget

#include "Basic.hpp"

#include "AthenaMOTDWatchVideoWidget_classes.hpp"
#include "AthenaMOTDWatchVideoWidget_parameters.hpp"


namespace SDK
{

// Function AthenaMOTDWatchVideoWidget.AthenaMOTDWatchVideoWidget_C.BindVideoEvents
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaMOTDWatchVideoWidget_C::BindVideoEvents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDWatchVideoWidget_C", "BindVideoEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaMOTDWatchVideoWidget.AthenaMOTDWatchVideoWidget_C.CloseWidgetNoURL
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaMOTDWatchVideoWidget_C::CloseWidgetNoURL()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDWatchVideoWidget_C", "CloseWidgetNoURL");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaMOTDWatchVideoWidget.AthenaMOTDWatchVideoWidget_C.CloseWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           URL                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UAthenaMOTDWatchVideoWidget_C::CloseWidget(const class FString& URL)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDWatchVideoWidget_C", "CloseWidget");

	Params::AthenaMOTDWatchVideoWidget_C_CloseWidget Parms{};

	Parms.URL = std::move(URL);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaMOTDWatchVideoWidget.AthenaMOTDWatchVideoWidget_C.OnPopulateNews
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FAthenaNewsEntry                 NewsEntry                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaMOTDWatchVideoWidget_C::OnPopulateNews(const struct FAthenaNewsEntry& NewsEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDWatchVideoWidget_C", "OnPopulateNews");

	Params::AthenaMOTDWatchVideoWidget_C_OnPopulateNews Parms{};

	Parms.NewsEntry = std::move(NewsEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaMOTDWatchVideoWidget.AthenaMOTDWatchVideoWidget_C.ExecuteUbergraph_AthenaMOTDWatchVideoWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaMOTDWatchVideoWidget_C::ExecuteUbergraph_AthenaMOTDWatchVideoWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDWatchVideoWidget_C", "ExecuteUbergraph_AthenaMOTDWatchVideoWidget");

	Params::AthenaMOTDWatchVideoWidget_C_ExecuteUbergraph_AthenaMOTDWatchVideoWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

