#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaMOTDLandingWidget

#include "Basic.hpp"

#include "AthenaMOTDLandingWidget_classes.hpp"
#include "AthenaMOTDLandingWidget_parameters.hpp"


namespace SDK
{

// Function AthenaMOTDLandingWidget.AthenaMOTDLandingWidget_C.SetTextIfValidOrDefault
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           String                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FText                             DefaultText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UAthenaMOTDLandingWidget_C::SetTextIfValidOrDefault(class UCommonButton* Button, const class FString& String, const class FText& DefaultText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDLandingWidget_C", "SetTextIfValidOrDefault");

	Params::AthenaMOTDLandingWidget_C_SetTextIfValidOrDefault Parms{};

	Parms.Button = Button;
	Parms.String = std::move(String);
	Parms.DefaultText = std::move(DefaultText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaMOTDLandingWidget.AthenaMOTDLandingWidget_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaMOTDLandingWidget_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDLandingWidget_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaMOTDLandingWidget.AthenaMOTDLandingWidget_C.OnPopulateNews
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FAthenaNewsEntry                 NewsEntry                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaMOTDLandingWidget_C::OnPopulateNews(const struct FAthenaNewsEntry& NewsEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDLandingWidget_C", "OnPopulateNews");

	Params::AthenaMOTDLandingWidget_C_OnPopulateNews Parms{};

	Parms.NewsEntry = std::move(NewsEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaMOTDLandingWidget.AthenaMOTDLandingWidget_C.ExecuteUbergraph_AthenaMOTDLandingWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaMOTDLandingWidget_C::ExecuteUbergraph_AthenaMOTDLandingWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMOTDLandingWidget_C", "ExecuteUbergraph_AthenaMOTDLandingWidget");

	Params::AthenaMOTDLandingWidget_C_ExecuteUbergraph_AthenaMOTDLandingWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

