#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Ranged_Ashton_Indigo_Athena

#include "Basic.hpp"

#include "B_Ranged_Ashton_Indigo_Athena_classes.hpp"
#include "B_Ranged_Ashton_Indigo_Athena_parameters.hpp"


namespace SDK
{

// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.ExecuteUbergraph_B_Ranged_Ashton_Indigo_Athena
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Ranged_Ashton_Indigo_Athena_C::ExecuteUbergraph_B_Ranged_Ashton_Indigo_Athena(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "ExecuteUbergraph_B_Ranged_Ashton_Indigo_Athena");

	Params::B_Ranged_Ashton_Indigo_Athena_C_ExecuteUbergraph_B_Ranged_Ashton_Indigo_Athena Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Ranged_Ashton_Indigo_Athena_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "ReceiveTick");

	Params::B_Ranged_Ashton_Indigo_Athena_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.NewTarget
// (BlueprintCallable, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::NewTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "NewTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.LockOnEnd
// (BlueprintCallable, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::LockOnEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "LockOnEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.LockOnStart
// (BlueprintCallable, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::LockOnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "LockOnStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.OnSpawnProjectile
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AFortProjectileBase*              SpawnProjectile                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Ranged_Ashton_Indigo_Athena_C::OnSpawnProjectile(class AFortProjectileBase* SpawnProjectile)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "OnSpawnProjectile");

	Params::B_Ranged_Ashton_Indigo_Athena_C_OnSpawnProjectile Parms{};

	Parms.SpawnProjectile = SpawnProjectile;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.OnSetTargeting
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bNewIsTargeting                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Ranged_Ashton_Indigo_Athena_C::OnSetTargeting(bool bNewIsTargeting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "OnSetTargeting");

	Params::B_Ranged_Ashton_Indigo_Athena_C_OnSetTargeting Parms{};

	Parms.bNewIsTargeting = bNewIsTargeting;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.BindOnHandFired
// (BlueprintCallable, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::BindOnHandFired()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "BindOnHandFired");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.HandFired
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EDualWeaponHand                         Hand                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bPersistantFire                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Ranged_Ashton_Indigo_Athena_C::HandFired(EDualWeaponHand Hand, bool bPersistantFire)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "HandFired");

	Params::B_Ranged_Ashton_Indigo_Athena_C_HandFired Parms{};

	Parms.Hand = Hand;
	Parms.bPersistantFire = bPersistantFire;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.OnWeaponAttached
// (Event, Public, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::OnWeaponAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "OnWeaponAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.K2_OnUnEquip
// (Event, Public, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::K2_OnUnEquip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "K2_OnUnEquip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.OnStopWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::OnStopWeaponFireFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "OnStopWeaponFireFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.OnPlayWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bPersistentFire                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bSecondaryFire                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Ranged_Ashton_Indigo_Athena_C::OnPlayWeaponFireFX(bool bPersistentFire, bool bSecondaryFire)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "OnPlayWeaponFireFX");

	Params::B_Ranged_Ashton_Indigo_Athena_C_OnPlayWeaponFireFX Parms{};

	Parms.bPersistentFire = bPersistentFire;
	Parms.bSecondaryFire = bSecondaryFire;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.Intensity__UpdateFunc
// (BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::Intensity__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "Intensity__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.Intensity__FinishedFunc
// (BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::Intensity__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "Intensity__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.CenterSize__UpdateFunc
// (BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::CenterSize__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "CenterSize__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.CenterSize__FinishedFunc
// (BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::CenterSize__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "CenterSize__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.CenterReset__UpdateFunc
// (BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::CenterReset__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "CenterReset__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.CenterReset__FinishedFunc
// (BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::CenterReset__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "CenterReset__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.HideReticle
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::HideReticle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "HideReticle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Ranged_Ashton_Indigo_Athena.B_Ranged_Ashton_Indigo_Athena_C.ShowReticle
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Ranged_Ashton_Indigo_Athena_C::ShowReticle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Ranged_Ashton_Indigo_Athena_C", "ShowReticle");

	UObject::ProcessEvent(Func, nullptr);
}

}

