#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Creative_Device_Teleporter

#include "Basic.hpp"

#include "BP_Creative_Device_Teleporter_classes.hpp"
#include "BP_Creative_Device_Teleporter_parameters.hpp"


namespace SDK
{

// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.ExecuteUbergraph_BP_Creative_Device_Teleporter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::ExecuteUbergraph_BP_Creative_Device_Teleporter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "ExecuteUbergraph_BP_Creative_Device_Teleporter");

	Params::BP_Creative_Device_Teleporter_C_ExecuteUbergraph_BP_Creative_Device_Teleporter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "ReceiveEndPlay");

	Params::BP_Creative_Device_Teleporter_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__TeleportToWhenReceived_K2Node_ComponentBoundEvent_7_OnGameplayMessageReceived__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AController*                      TriggerInstigator                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__TeleportToWhenReceived_K2Node_ComponentBoundEvent_7_OnGameplayMessageReceived__DelegateSignature(class AController* TriggerInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__TeleportToWhenReceived_K2Node_ComponentBoundEvent_7_OnGameplayMessageReceived__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__TeleportToWhenReceived_K2Node_ComponentBoundEvent_7_OnGameplayMessageReceived__DelegateSignature Parms{};

	Parms.TriggerInstigator = TriggerInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_13_OnMinigameAssignmentChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AFortMinigame*                    Minigame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_13_OnMinigameAssignmentChanged__DelegateSignature(class AFortMinigame* Minigame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_13_OnMinigameAssignmentChanged__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_13_OnMinigameAssignmentChanged__DelegateSignature Parms{};

	Parms.Minigame = Minigame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__EnabledComponent_K2Node_ComponentBoundEvent_12_On Enabled State Changed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Creative_Device_Teleporter_C::BndEvt__EnabledComponent_K2Node_ComponentBoundEvent_12_On_Enabled_State_Changed__DelegateSignature(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__EnabledComponent_K2Node_ComponentBoundEvent_12_On Enabled State Changed__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__EnabledComponent_K2Node_ComponentBoundEvent_12_On_Enabled_State_Changed__DelegateSignature Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__EnergyComponent_K2Node_ComponentBoundEvent_11_EnergyLevelsUpdated__DelegateSignature
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::BndEvt__EnergyComponent_K2Node_ComponentBoundEvent_11_EnergyLevelsUpdated__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__EnergyComponent_K2Node_ComponentBoundEvent_11_EnergyLevelsUpdated__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_6_OnMinigameStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AFortMinigame*                    Minigame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortMinigameState                      NewMinigameState                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_6_OnMinigameStateChanged__DelegateSignature(class AFortMinigame* Minigame, EFortMinigameState NewMinigameState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_6_OnMinigameStateChanged__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_6_OnMinigameStateChanged__DelegateSignature Parms{};

	Parms.Minigame = Minigame;
	Parms.NewMinigameState = NewMinigameState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.UpdateRiftVisibility
// (BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::UpdateRiftVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "UpdateRiftVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_9_SimpleDynamicMulticastDelegate__DelegateSignature
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_9_SimpleDynamicMulticastDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_9_SimpleDynamicMulticastDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_8_SimpleDynamicMulticastDelegate__DelegateSignature
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_8_SimpleDynamicMulticastDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__FortMinigameLogic_K2Node_ComponentBoundEvent_8_SimpleDynamicMulticastDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.PlayTeleportEnteredFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::PlayTeleportEnteredFX(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "PlayTeleportEnteredFX");

	Params::BP_Creative_Device_Teleporter_C_PlayTeleportEnteredFX Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__ToyOptionsComponent_K2Node_ComponentBoundEvent_5_AnyPropertyChangedDelegate__DelegateSignature
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::BndEvt__ToyOptionsComponent_K2Node_ComponentBoundEvent_5_AnyPropertyChangedDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__ToyOptionsComponent_K2Node_ComponentBoundEvent_5_AnyPropertyChangedDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__RechargeWhenReceived_K2Node_ComponentBoundEvent_4_OnGameplayMessageReceived__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AController*                      TriggerInstigator                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__RechargeWhenReceived_K2Node_ComponentBoundEvent_4_OnGameplayMessageReceived__DelegateSignature(class AController* TriggerInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__RechargeWhenReceived_K2Node_ComponentBoundEvent_4_OnGameplayMessageReceived__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__RechargeWhenReceived_K2Node_ComponentBoundEvent_4_OnGameplayMessageReceived__DelegateSignature Parms{};

	Parms.TriggerInstigator = TriggerInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__DrainEnergyWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AController*                      TriggerInstigator                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__DrainEnergyWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature(class AController* TriggerInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__DrainEnergyWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__DrainEnergyWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature Parms{};

	Parms.TriggerInstigator = TriggerInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__OverlapCapsule_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Creative_Device_Teleporter_C::BndEvt__OverlapCapsule_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__OverlapCapsule_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__OverlapCapsule_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__DisableWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AController*                      TriggerInstigator                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__DisableWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature(class AController* TriggerInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__DisableWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__DisableWhenReceived_K2Node_ComponentBoundEvent_1_OnGameplayMessageReceived__DelegateSignature Parms{};

	Parms.TriggerInstigator = TriggerInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BndEvt__EnableWhenReceived_K2Node_ComponentBoundEvent_0_OnGameplayMessageReceived__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AController*                      TriggerInstigator                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::BndEvt__EnableWhenReceived_K2Node_ComponentBoundEvent_0_OnGameplayMessageReceived__DelegateSignature(class AController* TriggerInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BndEvt__EnableWhenReceived_K2Node_ComponentBoundEvent_0_OnGameplayMessageReceived__DelegateSignature");

	Params::BP_Creative_Device_Teleporter_C_BndEvt__EnableWhenReceived_K2Node_ComponentBoundEvent_0_OnGameplayMessageReceived__DelegateSignature Parms{};

	Parms.TriggerInstigator = TriggerInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.PlayTeleportExitedFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::PlayTeleportExitedFX(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "PlayTeleportExitedFX");

	Params::BP_Creative_Device_Teleporter_C_PlayTeleportExitedFX Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.PortalDisabledFX
// (BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::PortalDisabledFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "PortalDisabledFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.PortalEnabledFX
// (BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::PortalEnabledFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "PortalEnabledFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.UpdateTeleporterFX
// (BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::UpdateTeleporterFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "UpdateTeleporterFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TPDisabledFXTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::TPDisabledFXTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TPDisabledFXTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TPDisabledFXTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::TPDisabledFXTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TPDisabledFXTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TPEnabledFXTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::TPEnabledFXTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TPEnabledFXTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TPEnabledFXTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::TPEnabledFXTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TPEnabledFXTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TPEffectsTimeLine__UpdateFunc
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::TPEffectsTimeLine__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TPEffectsTimeLine__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TPEffectsTimeLine__FinishedFunc
// (BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::TPEffectsTimeLine__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TPEffectsTimeLine__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.CanTeleportActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPawn*                        PawnToTeleport_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bCanTeleportActor                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Creative_Device_Teleporter_C::CanTeleportActor(class AFortPawn* PawnToTeleport_0, bool* bCanTeleportActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "CanTeleportActor");

	Params::BP_Creative_Device_Teleporter_C_CanTeleportActor Parms{};

	Parms.PawnToTeleport_0 = PawnToTeleport_0;

	UObject::ProcessEvent(Func, &Parms);

	if (bCanTeleportActor != nullptr)
		*bCanTeleportActor = Parms.bCanTeleportActor;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.GetTeleporterManager
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortCreativeTeleporterManagerComponent*TeleporterManagerComponent                             (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::GetTeleporterManager(class UFortCreativeTeleporterManagerComponent** TeleporterManagerComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "GetTeleporterManager");

	Params::BP_Creative_Device_Teleporter_C_GetTeleporterManager Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TeleporterManagerComponent != nullptr)
		*TeleporterManagerComponent = Parms.TeleporterManagerComponent;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.TeleportPlayerPawnTo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PawnToTeleport_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_Creative_Device_Teleporter_C* TargetTeleporter                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::TeleportPlayerPawnTo(class AFortPlayerPawn* PawnToTeleport_0, class ABP_Creative_Device_Teleporter_C* TargetTeleporter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "TeleportPlayerPawnTo");

	Params::BP_Creative_Device_Teleporter_C_TeleportPlayerPawnTo Parms{};

	Parms.PawnToTeleport_0 = PawnToTeleport_0;
	Parms.TargetTeleporter = TargetTeleporter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.isMinigameInProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInProgress                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Creative_Device_Teleporter_C::isMinigameInProgress(bool* bInProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "isMinigameInProgress");

	Params::BP_Creative_Device_Teleporter_C_isMinigameInProgress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bInProgress != nullptr)
		*bInProgress = Parms.bInProgress;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.SelectDestinationTeleporter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PawnToTeleport_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_Creative_Device_Teleporter_C* SelectedTeleporter                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::SelectDestinationTeleporter(class AFortPlayerPawn* PawnToTeleport_0, class ABP_Creative_Device_Teleporter_C** SelectedTeleporter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "SelectDestinationTeleporter");

	Params::BP_Creative_Device_Teleporter_C_SelectDestinationTeleporter Parms{};

	Parms.PawnToTeleport_0 = PawnToTeleport_0;

	UObject::ProcessEvent(Func, &Parms);

	if (SelectedTeleporter != nullptr)
		*SelectedTeleporter = Parms.SelectedTeleporter;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.UpdateEnergyAttributes
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::UpdateEnergyAttributes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "UpdateEnergyAttributes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.InitializeFX
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::InitializeFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "InitializeFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.isMinigameInCreationMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInCreationMode                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Creative_Device_Teleporter_C::isMinigameInCreationMode(bool* bInCreationMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "isMinigameInCreationMode");

	Params::BP_Creative_Device_Teleporter_C_isMinigameInCreationMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bInCreationMode != nullptr)
		*bInCreationMode = Parms.bInCreationMode;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.OnReceivedPawn
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PawnReceived                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::OnReceivedPawn(class AFortPlayerPawn* PawnReceived)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "OnReceivedPawn");

	Params::BP_Creative_Device_Teleporter_C_OnReceivedPawn Parms{};

	Parms.PawnReceived = PawnReceived;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.OnRep_TeleporterUsedFlash
// (BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::OnRep_TeleporterUsedFlash()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "OnRep_TeleporterUsedFlash");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.ResetTeleportEventState
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Creative_Device_Teleporter_C::ResetTeleportEventState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "ResetTeleportEventState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.GetTeleportedPawnYaw
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PawnToTeleport_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_Creative_Device_Teleporter_C* SourceTeleporter                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OutYaw                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::GetTeleportedPawnYaw(class AFortPlayerPawn* PawnToTeleport_0, class ABP_Creative_Device_Teleporter_C* SourceTeleporter, float* OutYaw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "GetTeleportedPawnYaw");

	Params::BP_Creative_Device_Teleporter_C_GetTeleportedPawnYaw Parms{};

	Parms.PawnToTeleport_0 = PawnToTeleport_0;
	Parms.SourceTeleporter = SourceTeleporter;

	UObject::ProcessEvent(Func, &Parms);

	if (OutYaw != nullptr)
		*OutYaw = Parms.OutYaw;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.GetTeleportedPawnPitch
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PawnToTeleport_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_Creative_Device_Teleporter_C* SourceTeleporter                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OutPitch                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Creative_Device_Teleporter_C::GetTeleportedPawnPitch(class AFortPlayerPawn* PawnToTeleport_0, class ABP_Creative_Device_Teleporter_C* SourceTeleporter, float* OutPitch)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "GetTeleportedPawnPitch");

	Params::BP_Creative_Device_Teleporter_C_GetTeleportedPawnPitch Parms{};

	Parms.PawnToTeleport_0 = PawnToTeleport_0;
	Parms.SourceTeleporter = SourceTeleporter;

	UObject::ProcessEvent(Func, &Parms);

	if (OutPitch != nullptr)
		*OutPitch = Parms.OutPitch;
}


// Function BP_Creative_Device_Teleporter.BP_Creative_Device_Teleporter_C.BlueprintCanInteract
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AFortPawn*                        InteractingPawn                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionBeingAttempted              InteractionBeingAttempted                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABP_Creative_Device_Teleporter_C::BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Creative_Device_Teleporter_C", "BlueprintCanInteract");

	Params::BP_Creative_Device_Teleporter_C_BlueprintCanInteract Parms{};

	Parms.InteractingPawn = InteractingPawn;
	Parms.InteractionBeingAttempted = InteractionBeingAttempted;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

