#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ContextTutorialIndicator

#include "Basic.hpp"

#include "ContextTutorialIndicator_classes.hpp"
#include "ContextTutorialIndicator_parameters.hpp"


namespace SDK
{

// Function ContextTutorialIndicator.ContextTutorialIndicator_C.ExecuteUbergraph_ContextTutorialIndicator
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UContextTutorialIndicator_C::ExecuteUbergraph_ContextTutorialIndicator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ContextTutorialIndicator_C", "ExecuteUbergraph_ContextTutorialIndicator");

	Params::ContextTutorialIndicator_C_ExecuteUbergraph_ContextTutorialIndicator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ContextTutorialIndicator.ContextTutorialIndicator_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UContextTutorialIndicator_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ContextTutorialIndicator_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

