#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Device_Ceiling_NoWeaponZone

#include "Basic.hpp"

#include "Device_Ceiling_NoWeaponZone_classes.hpp"
#include "Device_Ceiling_NoWeaponZone_parameters.hpp"


namespace SDK
{

// Function Device_Ceiling_NoWeaponZone.Device_Ceiling_NoWeaponZone_C.GetTriggerLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADevice_Ceiling_NoWeaponZone_C::GetTriggerLocation(struct FVector* Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Device_Ceiling_NoWeaponZone_C", "GetTriggerLocation");

	Params::Device_Ceiling_NoWeaponZone_C_GetTriggerLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);
}

}

