#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Galileo_Evaluator_FollowPatrolPath

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Galileo_Evaluator_FollowPatrolPath.Galileo_Evaluator_FollowPatrolPath_C
// 0x0000 (0x0170 - 0x0170)
class UGalileo_Evaluator_FollowPatrolPath_C final : public UFortAthenaNpcEvaluator_FollowPatrolPath
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Galileo_Evaluator_FollowPatrolPath_C">();
	}
	static class UGalileo_Evaluator_FollowPatrolPath_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGalileo_Evaluator_FollowPatrolPath_C>();
	}
};
static_assert(alignof(UGalileo_Evaluator_FollowPatrolPath_C) == 0x000008, "Wrong alignment on UGalileo_Evaluator_FollowPatrolPath_C");
static_assert(sizeof(UGalileo_Evaluator_FollowPatrolPath_C) == 0x000170, "Wrong size on UGalileo_Evaluator_FollowPatrolPath_C");

}

