#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Creative_EliminationZone_DOT_Player

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Creative_EliminationZone_DOT_Player.GCNL_Creative_EliminationZone_DOT_Player_C
// 0x0000 (0x0788 - 0x0788)
class AGCNL_Creative_EliminationZone_DOT_Player_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_Creative_EliminationZone_DOT_Player_C">();
	}
	static class AGCNL_Creative_EliminationZone_DOT_Player_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Creative_EliminationZone_DOT_Player_C>();
	}
};
static_assert(alignof(AGCNL_Creative_EliminationZone_DOT_Player_C) == 0x000008, "Wrong alignment on AGCNL_Creative_EliminationZone_DOT_Player_C");
static_assert(sizeof(AGCNL_Creative_EliminationZone_DOT_Player_C) == 0x000788, "Wrong size on AGCNL_Creative_EliminationZone_DOT_Player_C");

}

