#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemPresentationScreen

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ItemPresentationScreen.ItemPresentationScreen_C.ExecuteUbergraph_ItemPresentationScreen
// 0x0380 (0x0380 - 0x0000)
struct ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UItemInfoPresentationWidget_C*          K2Node_DynamicCast_AsItem_Info_Presentation_Widget; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UItemInfoPresentationWidget_C*          K2Node_DynamicCast_AsItem_Info_Presentation_Widget_1; // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetDisplayedEntryWidgets_ReturnValue;     // 0x0030(0x0010)(ConstParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUserWidget*>                    CallFunc_GetAllEntries_ReturnValue;                // 0x0050(0x0010)(ConstParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UItemPresentationGenericRewardHeader_C* K2Node_DynamicCast_AsItem_Presentation_Generic_Reward_Header; // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UItemPresentationGenericRewardHeader_C* K2Node_DynamicCast_AsItem_Presentation_Generic_Reward_Header_1; // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              CallFunc_GetVisibility_ReturnValue;                // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0092(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_93[0x1];                                       // 0x0093(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortItemHeaderInformation             K2Node_Event_HeaderInformation;                    // 0x00A0(0x0098)(ConstParm)
	const class UFortItem*                        K2Node_Event_FortItem;                             // 0x0138(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bShowText;                            // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bUsingListView;                       // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUserWidget*>                    CallFunc_GetDisplayedEntryWidgets_ReturnValue_1;   // 0x0158(0x0010)(ConstParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x0168(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Array_Get_Item_1;                         // 0x0170(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UItemPresentationEntry_C*               K2Node_DynamicCast_AsItem_Presentation_Entry;      // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UItemPresentationEntry_C*               K2Node_DynamicCast_AsItem_Presentation_Entry_1;    // 0x0188(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_IntFloat_ReturnValue;            // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetAllEntries_ReturnValue_1;              // 0x0198(0x0010)(ConstParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference)
	class UUserWidget*                            CallFunc_Array_Get_Item_2;                         // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UItemPresentationEntry_C*               K2Node_DynamicCast_AsItem_Presentation_Entry_2;    // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x3];                                      // 0x01B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x01BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCanEquip;                            // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C1[0x3];                                      // 0x01C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_Array_Get_Item_3;                         // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_IntFloat_ReturnValue_1;          // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D4[0x4];                                      // 0x01D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UItemPresentationEntry_C*               K2Node_DynamicCast_AsItem_Presentation_Entry_3;    // 0x01D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bShowNext;                            // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E2[0x6];                                      // 0x01E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USoloButton_C*                          K2Node_DynamicCast_AsSolo_Button;                  // 0x01E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bShowOtherRewards;                    // 0x01F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bCloseScreen;                         // 0x01F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F3[0x5];                                      // 0x01F3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_1;        // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue_1;       // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_211[0x7];                                      // 0x0211(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoloButton_C*                          K2Node_DynamicCast_AsSolo_Button_1;                // 0x0218(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_221[0x7];                                      // 0x0221(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    K2Node_MakeStruct_DataTableRowHandle;              // 0x0228(0x0010)(NoDestructor)
	class UItemInfoPresentationWidget_C*          K2Node_DynamicCast_AsItem_Info_Presentation_Widget_2; // 0x0238(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_241[0x7];                                      // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassTracker_C*                   K2Node_DynamicCast_AsBattle_Pass_Tracker;          // 0x0248(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassTracker_C*                   K2Node_DynamicCast_AsBattle_Pass_Tracker_1;        // 0x0258(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_12;                    // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassItemTracker_C*               K2Node_DynamicCast_AsBattle_Pass_Item_Tracker;     // 0x0268(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_13;                    // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_271[0x7];                                      // 0x0271(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassItemTracker_C*               K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_1;   // 0x0278(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_14;                    // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassItemTracker_C*               K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_2;   // 0x0288(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_15;                    // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassTracker_C*                   K2Node_DynamicCast_AsBattle_Pass_Tracker_2;        // 0x0298(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_16;                    // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassTracker_C*                   K2Node_DynamicCast_AsBattle_Pass_Tracker_3;        // 0x02A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_17;                    // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattlePassItemTracker_C*               K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_3;   // 0x02B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_18;                    // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C1[0x7];                                      // 0x02C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_2;              // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class AFortItemPreviewVaultWorld*       K2Node_Event_FortItemPreviewVaultWorld;            // 0x02D0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSpecialEventRewards;               // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AFrontendCamera_VaultRotator_C*> CallFunc_GetAllActorsOfClass_OutActors;            // 0x02E0(0x0010)(ZeroConstructor, ReferenceParm)
	class AFrontendCamera_VaultRotator_C*         CallFunc_Array_Get_Item_4;                         // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ActorHasTag_ReturnValue;                  // 0x02FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2FD[0x3];                                      // 0x02FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AVaultWorld_C*                          K2Node_DynamicCast_AsVault_World;                  // 0x0300(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_19;                    // 0x0308(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_309[0x7];                                      // 0x0309(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AVaultRotator_C*                        CallFunc_GetVaultRotator_VaultRotator;             // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31D[0x3];                                      // 0x031D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0320(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0324(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_325[0x3];                                      // 0x0325(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext*                   CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AFrontendCamera_VaultRotator_C*> CallFunc_GetAllActorsOfClass_OutActors_1;          // 0x0330(0x0010)(ZeroConstructor, ReferenceParm)
	class AFrontendCamera_VaultRotator_C*         CallFunc_Array_Get_Item_5;                         // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0348(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x034C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ActorHasTag_ReturnValue_1;                // 0x034D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x034E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsWinterfestReward;                  // 0x034F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FLinearColor                           K2Node_Event_PresentColor;                         // 0x0350(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_1;         // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoloButton_WinterFest_C*               K2Node_DynamicCast_AsSolo_Button_Winter_Fest;      // 0x0370(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_20;                    // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen");
static_assert(sizeof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen) == 0x000380, "Wrong size on ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, EntryPoint) == 0x000000, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_bool_True_if_break_was_hit_Variable) == 0x000004, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Array_Index_Variable) == 0x000008, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Not_PreBool_ReturnValue) == 0x00000C, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Info_Presentation_Widget) == 0x000010, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Info_Presentation_Widget' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Info_Presentation_Widget_1) == 0x000020, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Info_Presentation_Widget_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_1) == 0x000028, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Loop_Counter_Variable) == 0x00002C, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetDisplayedEntryWidgets_ReturnValue) == 0x000030, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetDisplayedEntryWidgets_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Add_IntInt_ReturnValue) == 0x000040, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Length_ReturnValue) == 0x000044, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Loop_Counter_Variable_1) == 0x000048, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Less_IntInt_ReturnValue) == 0x00004C, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetAllEntries_ReturnValue) == 0x000050, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetAllEntries_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Length_ReturnValue_1) == 0x000060, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Add_IntInt_ReturnValue_1) == 0x000064, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Less_IntInt_ReturnValue_1) == 0x000068, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_PlayAnimationForward_ReturnValue) == 0x000070, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Presentation_Generic_Reward_Header) == 0x000078, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Presentation_Generic_Reward_Header' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_2) == 0x000080, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Presentation_Generic_Reward_Header_1) == 0x000088, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Presentation_Generic_Reward_Header_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_3) == 0x000090, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetVisibility_ReturnValue) == 0x000091, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetVisibility_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000092, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Loop_Counter_Variable_2) == 0x000094, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Add_IntInt_ReturnValue_2) == 0x000098, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_HeaderInformation) == 0x0000A0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_HeaderInformation' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_FortItem) == 0x000138, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_FortItem' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bShowText) == 0x000140, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bShowText' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bUsingListView) == 0x000141, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bUsingListView' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_PlayAnimation_ReturnValue) == 0x000148, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Array_Index_Variable_1) == 0x000150, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetDisplayedEntryWidgets_ReturnValue_1) == 0x000158, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetDisplayedEntryWidgets_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Get_Item) == 0x000168, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Get_Item_1) == 0x000170, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Presentation_Entry) == 0x000178, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Presentation_Entry' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_4) == 0x000180, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Presentation_Entry_1) == 0x000188, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Presentation_Entry_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_5) == 0x000190, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Multiply_IntFloat_ReturnValue) == 0x000194, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Multiply_IntFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetAllEntries_ReturnValue_1) == 0x000198, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetAllEntries_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Get_Item_2) == 0x0001A8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Presentation_Entry_2) == 0x0001B0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Presentation_Entry_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_6) == 0x0001B8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Array_Index_Variable_2) == 0x0001BC, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bCanEquip) == 0x0001C0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bCanEquip' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Array_Index_Variable_3) == 0x0001C4, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Get_Item_3) == 0x0001C8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Multiply_IntFloat_ReturnValue_1) == 0x0001D0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Multiply_IntFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Presentation_Entry_3) == 0x0001D8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Presentation_Entry_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_7) == 0x0001E0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bShowNext) == 0x0001E1, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bShowNext' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsSolo_Button) == 0x0001E8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsSolo_Button' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_8) == 0x0001F0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bShowOtherRewards) == 0x0001F1, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bShowOtherRewards' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bCloseScreen) == 0x0001F2, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bCloseScreen' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_PlayAnimation_ReturnValue_1) == 0x0001F8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_bool_True_if_break_was_hit_Variable_1) == 0x000200, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_bool_True_if_break_was_hit_Variable_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_PlayAnimationForward_ReturnValue_1) == 0x000208, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_PlayAnimationForward_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Not_PreBool_ReturnValue_1) == 0x000210, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsSolo_Button_1) == 0x000218, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsSolo_Button_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_9) == 0x000220, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_MakeStruct_DataTableRowHandle) == 0x000228, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_MakeStruct_DataTableRowHandle' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsItem_Info_Presentation_Widget_2) == 0x000238, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsItem_Info_Presentation_Widget_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_10) == 0x000240, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Tracker) == 0x000248, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Tracker' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_11) == 0x000250, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_11' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Tracker_1) == 0x000258, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Tracker_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_12) == 0x000260, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_12' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Item_Tracker) == 0x000268, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Item_Tracker' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_13) == 0x000270, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_13' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_1) == 0x000278, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_14) == 0x000280, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_14' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_2) == 0x000288, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_15) == 0x000290, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_15' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Tracker_2) == 0x000298, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Tracker_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_16) == 0x0002A0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_16' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Tracker_3) == 0x0002A8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Tracker_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_17) == 0x0002B0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_17' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_3) == 0x0002B8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsBattle_Pass_Item_Tracker_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_18) == 0x0002C0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_18' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_PlayAnimation_ReturnValue_2) == 0x0002C8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_PlayAnimation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_FortItemPreviewVaultWorld) == 0x0002D0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_FortItemPreviewVaultWorld' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bIsSpecialEventRewards) == 0x0002D8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bIsSpecialEventRewards' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetAllActorsOfClass_OutActors) == 0x0002E0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Get_Item_4) == 0x0002F0, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Length_ReturnValue_2) == 0x0002F8, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_ActorHasTag_ReturnValue) == 0x0002FC, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_ActorHasTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsVault_World) == 0x000300, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsVault_World' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_19) == 0x000308, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_19' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetVaultRotator_VaultRotator) == 0x000310, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetVaultRotator_VaultRotator' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, Temp_int_Loop_Counter_Variable_3) == 0x000318, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Less_IntInt_ReturnValue_2) == 0x00031C, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Add_IntInt_ReturnValue_3) == 0x000320, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_BooleanAND_ReturnValue) == 0x000324, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000328, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetAllActorsOfClass_OutActors_1) == 0x000330, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetAllActorsOfClass_OutActors_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Get_Item_5) == 0x000340, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Array_Length_ReturnValue_3) == 0x000348, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_Less_IntInt_ReturnValue_3) == 0x00034C, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_ActorHasTag_ReturnValue_1) == 0x00034D, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_ActorHasTag_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_BooleanAND_ReturnValue_1) == 0x00034E, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_bIsWinterfestReward) == 0x00034F, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_bIsWinterfestReward' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_Event_PresentColor) == 0x000350, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_Event_PresentColor' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000360, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, CallFunc_GetDynamicMaterial_ReturnValue_1) == 0x000368, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::CallFunc_GetDynamicMaterial_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_AsSolo_Button_Winter_Fest) == 0x000370, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_AsSolo_Button_Winter_Fest' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen, K2Node_DynamicCast_bSuccess_20) == 0x000378, "Member 'ItemPresentationScreen_C_ExecuteUbergraph_ItemPresentationScreen::K2Node_DynamicCast_bSuccess_20' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnUpdateGradientColor
// 0x0014 (0x0014 - 0x0000)
struct ItemPresentationScreen_C_OnUpdateGradientColor final
{
public:
	bool                                          bIsWinterfestReward;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           PresentColor;                                      // 0x0004(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemPresentationScreen_C_OnUpdateGradientColor) == 0x000004, "Wrong alignment on ItemPresentationScreen_C_OnUpdateGradientColor");
static_assert(sizeof(ItemPresentationScreen_C_OnUpdateGradientColor) == 0x000014, "Wrong size on ItemPresentationScreen_C_OnUpdateGradientColor");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateGradientColor, bIsWinterfestReward) == 0x000000, "Member 'ItemPresentationScreen_C_OnUpdateGradientColor::bIsWinterfestReward' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateGradientColor, PresentColor) == 0x000004, "Member 'ItemPresentationScreen_C_OnUpdateGradientColor::PresentColor' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnUpdateVaultWorld
// 0x0010 (0x0010 - 0x0000)
struct ItemPresentationScreen_C_OnUpdateVaultWorld final
{
public:
	const class AFortItemPreviewVaultWorld*       FortItemPreviewVaultWorld;                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSpecialEventRewards;                            // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnUpdateVaultWorld) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_OnUpdateVaultWorld");
static_assert(sizeof(ItemPresentationScreen_C_OnUpdateVaultWorld) == 0x000010, "Wrong size on ItemPresentationScreen_C_OnUpdateVaultWorld");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateVaultWorld, FortItemPreviewVaultWorld) == 0x000000, "Member 'ItemPresentationScreen_C_OnUpdateVaultWorld::FortItemPreviewVaultWorld' has a wrong offset!");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateVaultWorld, bIsSpecialEventRewards) == 0x000008, "Member 'ItemPresentationScreen_C_OnUpdateVaultWorld::bIsSpecialEventRewards' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnDisplayItemsCollectedText
// 0x0001 (0x0001 - 0x0000)
struct ItemPresentationScreen_C_OnDisplayItemsCollectedText final
{
public:
	bool                                          bCloseScreen;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnDisplayItemsCollectedText) == 0x000001, "Wrong alignment on ItemPresentationScreen_C_OnDisplayItemsCollectedText");
static_assert(sizeof(ItemPresentationScreen_C_OnDisplayItemsCollectedText) == 0x000001, "Wrong size on ItemPresentationScreen_C_OnDisplayItemsCollectedText");
static_assert(offsetof(ItemPresentationScreen_C_OnDisplayItemsCollectedText, bCloseScreen) == 0x000000, "Member 'ItemPresentationScreen_C_OnDisplayItemsCollectedText::bCloseScreen' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnFinishDisplayingHotItems
// 0x0001 (0x0001 - 0x0000)
struct ItemPresentationScreen_C_OnFinishDisplayingHotItems final
{
public:
	bool                                          bShowOtherRewards;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnFinishDisplayingHotItems) == 0x000001, "Wrong alignment on ItemPresentationScreen_C_OnFinishDisplayingHotItems");
static_assert(sizeof(ItemPresentationScreen_C_OnFinishDisplayingHotItems) == 0x000001, "Wrong size on ItemPresentationScreen_C_OnFinishDisplayingHotItems");
static_assert(offsetof(ItemPresentationScreen_C_OnFinishDisplayingHotItems, bShowOtherRewards) == 0x000000, "Member 'ItemPresentationScreen_C_OnFinishDisplayingHotItems::bShowOtherRewards' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnUpdateNextButtonText
// 0x0001 (0x0001 - 0x0000)
struct ItemPresentationScreen_C_OnUpdateNextButtonText final
{
public:
	bool                                          bShowNext;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnUpdateNextButtonText) == 0x000001, "Wrong alignment on ItemPresentationScreen_C_OnUpdateNextButtonText");
static_assert(sizeof(ItemPresentationScreen_C_OnUpdateNextButtonText) == 0x000001, "Wrong size on ItemPresentationScreen_C_OnUpdateNextButtonText");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateNextButtonText, bShowNext) == 0x000000, "Member 'ItemPresentationScreen_C_OnUpdateNextButtonText::bShowNext' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnDisplayEquipButton
// 0x0001 (0x0001 - 0x0000)
struct ItemPresentationScreen_C_OnDisplayEquipButton final
{
public:
	bool                                          bCanEquip;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnDisplayEquipButton) == 0x000001, "Wrong alignment on ItemPresentationScreen_C_OnDisplayEquipButton");
static_assert(sizeof(ItemPresentationScreen_C_OnDisplayEquipButton) == 0x000001, "Wrong size on ItemPresentationScreen_C_OnDisplayEquipButton");
static_assert(offsetof(ItemPresentationScreen_C_OnDisplayEquipButton, bCanEquip) == 0x000000, "Member 'ItemPresentationScreen_C_OnDisplayEquipButton::bCanEquip' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnInitialIconAnimation
// 0x0001 (0x0001 - 0x0000)
struct ItemPresentationScreen_C_OnInitialIconAnimation final
{
public:
	bool                                          bUsingListView;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnInitialIconAnimation) == 0x000001, "Wrong alignment on ItemPresentationScreen_C_OnInitialIconAnimation");
static_assert(sizeof(ItemPresentationScreen_C_OnInitialIconAnimation) == 0x000001, "Wrong size on ItemPresentationScreen_C_OnInitialIconAnimation");
static_assert(offsetof(ItemPresentationScreen_C_OnInitialIconAnimation, bUsingListView) == 0x000000, "Member 'ItemPresentationScreen_C_OnInitialIconAnimation::bUsingListView' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnUpdateOwnedItemText
// 0x0001 (0x0001 - 0x0000)
struct ItemPresentationScreen_C_OnUpdateOwnedItemText final
{
public:
	bool                                          bShowText;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemPresentationScreen_C_OnUpdateOwnedItemText) == 0x000001, "Wrong alignment on ItemPresentationScreen_C_OnUpdateOwnedItemText");
static_assert(sizeof(ItemPresentationScreen_C_OnUpdateOwnedItemText) == 0x000001, "Wrong size on ItemPresentationScreen_C_OnUpdateOwnedItemText");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateOwnedItemText, bShowText) == 0x000000, "Member 'ItemPresentationScreen_C_OnUpdateOwnedItemText::bShowText' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.Handle Animation InitialState
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationScreen_C_Handle_Animation_InitialState final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemPresentationScreen_C_Handle_Animation_InitialState) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_Handle_Animation_InitialState");
static_assert(sizeof(ItemPresentationScreen_C_Handle_Animation_InitialState) == 0x000008, "Wrong size on ItemPresentationScreen_C_Handle_Animation_InitialState");
static_assert(offsetof(ItemPresentationScreen_C_Handle_Animation_InitialState, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'ItemPresentationScreen_C_Handle_Animation_InitialState::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.Handle Fade
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationScreen_C_Handle_Fade final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemPresentationScreen_C_Handle_Fade) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_Handle_Fade");
static_assert(sizeof(ItemPresentationScreen_C_Handle_Fade) == 0x000008, "Wrong size on ItemPresentationScreen_C_Handle_Fade");
static_assert(offsetof(ItemPresentationScreen_C_Handle_Fade, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'ItemPresentationScreen_C_Handle_Fade::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.Handle Intro
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationScreen_C_Handle_Intro final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemPresentationScreen_C_Handle_Intro) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_Handle_Intro");
static_assert(sizeof(ItemPresentationScreen_C_Handle_Intro) == 0x000008, "Wrong size on ItemPresentationScreen_C_Handle_Intro");
static_assert(offsetof(ItemPresentationScreen_C_Handle_Intro, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'ItemPresentationScreen_C_Handle_Intro::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.Handle PaidItem Intro
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationScreen_C_Handle_PaidItem_Intro final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemPresentationScreen_C_Handle_PaidItem_Intro) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_Handle_PaidItem_Intro");
static_assert(sizeof(ItemPresentationScreen_C_Handle_PaidItem_Intro) == 0x000008, "Wrong size on ItemPresentationScreen_C_Handle_PaidItem_Intro");
static_assert(offsetof(ItemPresentationScreen_C_Handle_PaidItem_Intro, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'ItemPresentationScreen_C_Handle_PaidItem_Intro::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnUpdateHeaderInformation
// 0x0098 (0x0098 - 0x0000)
struct ItemPresentationScreen_C_OnUpdateHeaderInformation final
{
public:
	struct FFortItemHeaderInformation             HeaderInformation;                                 // 0x0000(0x0098)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(ItemPresentationScreen_C_OnUpdateHeaderInformation) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_OnUpdateHeaderInformation");
static_assert(sizeof(ItemPresentationScreen_C_OnUpdateHeaderInformation) == 0x000098, "Wrong size on ItemPresentationScreen_C_OnUpdateHeaderInformation");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateHeaderInformation, HeaderInformation) == 0x000000, "Member 'ItemPresentationScreen_C_OnUpdateHeaderInformation::HeaderInformation' has a wrong offset!");

// Function ItemPresentationScreen.ItemPresentationScreen_C.OnUpdateItemInformation
// 0x0008 (0x0008 - 0x0000)
struct ItemPresentationScreen_C_OnUpdateItemInformation final
{
public:
	const class UFortItem*                        FortItem;                                          // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemPresentationScreen_C_OnUpdateItemInformation) == 0x000008, "Wrong alignment on ItemPresentationScreen_C_OnUpdateItemInformation");
static_assert(sizeof(ItemPresentationScreen_C_OnUpdateItemInformation) == 0x000008, "Wrong size on ItemPresentationScreen_C_OnUpdateItemInformation");
static_assert(offsetof(ItemPresentationScreen_C_OnUpdateItemInformation, FortItem) == 0x000000, "Member 'ItemPresentationScreen_C_OnUpdateItemInformation::FortItem' has a wrong offset!");

}

