#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RealMoneyStorefront

#include "Basic.hpp"

#include "RealMoneyStorefront_classes.hpp"
#include "RealMoneyStorefront_parameters.hpp"


namespace SDK
{

// Function RealMoneyStorefront.RealMoneyStorefront_C.OnSectionEstablished
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bEmptySection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void URealMoneyStorefront_C::OnSectionEstablished(bool bEmptySection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RealMoneyStorefront_C", "OnSectionEstablished");

	Params::RealMoneyStorefront_C_OnSectionEstablished Parms{};

	Parms.bEmptySection = bEmptySection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RealMoneyStorefront.RealMoneyStorefront_C.ExecuteUbergraph_RealMoneyStorefront
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URealMoneyStorefront_C::ExecuteUbergraph_RealMoneyStorefront(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RealMoneyStorefront_C", "ExecuteUbergraph_RealMoneyStorefront");

	Params::RealMoneyStorefront_C_ExecuteUbergraph_RealMoneyStorefront Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

