#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandaloneSection

#include "Basic.hpp"

#include "StandaloneSection_classes.hpp"
#include "StandaloneSection_parameters.hpp"


namespace SDK
{

// Function StandaloneSection.StandaloneSection_C.OnSectionEstablished
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bEmptySection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UStandaloneSection_C::OnSectionEstablished(bool bEmptySection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StandaloneSection_C", "OnSectionEstablished");

	Params::StandaloneSection_C_OnSectionEstablished Parms{};

	Parms.bEmptySection = bEmptySection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StandaloneSection.StandaloneSection_C.ExecuteUbergraph_StandaloneSection
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStandaloneSection_C::ExecuteUbergraph_StandaloneSection(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StandaloneSection_C", "ExecuteUbergraph_StandaloneSection");

	Params::StandaloneSection_C_ExecuteUbergraph_StandaloneSection Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

