#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SubgameSelectFrontend

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SubgameSelectFrontend.SubgameSelectFrontend_C
// 0x0000 (0x02E0 - 0x02E0)
class USubgameSelectFrontend_C final : public UStartUpUIStateWidget_SubgameSelect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SubgameSelectFrontend_C">();
	}
	static class USubgameSelectFrontend_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USubgameSelectFrontend_C>();
	}
};
static_assert(alignof(USubgameSelectFrontend_C) == 0x000008, "Wrong alignment on USubgameSelectFrontend_C");
static_assert(sizeof(USubgameSelectFrontend_C) == 0x0002E0, "Wrong size on USubgameSelectFrontend_C");

}

