#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WinterQuest_MoreInfo_DetailsScreen

#include "Basic.hpp"

#include "WinterQuest_MoreInfo_DetailsScreen_classes.hpp"
#include "WinterQuest_MoreInfo_DetailsScreen_parameters.hpp"


namespace SDK
{

// Function WinterQuest_MoreInfo_DetailsScreen.WinterQuest_MoreInfo_DetailsScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWinterQuest_MoreInfo_DetailsScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WinterQuest_MoreInfo_DetailsScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WinterQuest_MoreInfo_DetailsScreen.WinterQuest_MoreInfo_DetailsScreen_C.BndEvt__SoloButton_WinterFest_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWinterQuest_MoreInfo_DetailsScreen_C::BndEvt__SoloButton_WinterFest_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WinterQuest_MoreInfo_DetailsScreen_C", "BndEvt__SoloButton_WinterFest_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");

	Params::WinterQuest_MoreInfo_DetailsScreen_C_BndEvt__SoloButton_WinterFest_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WinterQuest_MoreInfo_DetailsScreen.WinterQuest_MoreInfo_DetailsScreen_C.ExecuteUbergraph_WinterQuest_MoreInfo_DetailsScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWinterQuest_MoreInfo_DetailsScreen_C::ExecuteUbergraph_WinterQuest_MoreInfo_DetailsScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WinterQuest_MoreInfo_DetailsScreen_C", "ExecuteUbergraph_WinterQuest_MoreInfo_DetailsScreen");

	Params::WinterQuest_MoreInfo_DetailsScreen_C_ExecuteUbergraph_WinterQuest_MoreInfo_DetailsScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

