#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WinterQuest_OpenPrompt

#include "Basic.hpp"

#include "WinterQuest_OpenPrompt_classes.hpp"
#include "WinterQuest_OpenPrompt_parameters.hpp"


namespace SDK
{

// Function WinterQuest_OpenPrompt.WinterQuest_OpenPrompt_C.OpenPromptIntroAnim
// (Public, BlueprintCallable, BlueprintEvent)

void UWinterQuest_OpenPrompt_C::OpenPromptIntroAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WinterQuest_OpenPrompt_C", "OpenPromptIntroAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WinterQuest_OpenPrompt.WinterQuest_OpenPrompt_C.StopPlayingHoldAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UWinterQuest_OpenPrompt_C::StopPlayingHoldAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WinterQuest_OpenPrompt_C", "StopPlayingHoldAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WinterQuest_OpenPrompt.WinterQuest_OpenPrompt_C.StartPlayingHoldAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UWinterQuest_OpenPrompt_C::StartPlayingHoldAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WinterQuest_OpenPrompt_C", "StartPlayingHoldAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

