#pragma once
#include <vector>
#include <string>


inline std::vector<std::string> BotDisplayNamesIG = {
       "&darkBeast&",
       "007Витек",
       "0mn1v0r378",
       "1337Sk1lz",
       "1Forest120",
       "1eyedInvent0r",
       "1Такой",
       "240KMH",
       "25_wütende_Affen",
       "2Xtrouble13",
       "2joãozinho_bh2",
       "2sweaty23",
       "360NoScoper29718",
       "360walkaway",
       "404Zurco",
       "42Wow47",
       "44Sedano44",
       "4Regionals",
       "4tnite4ever15",
       "5HoleSniper",
       "5boysindahouse",
       "5p4cc07u770",
       "688.Hitman",
       "8BallWasHere",
       "9000Hippos",
       "90cranker7",
       "90sRunner",
       "9Яков",
       "A Sweaty Dog",
       "ADudeNamedPhil",
       "AGenuineHuman",
       "AGoodOmen",
       "ALLCAPS67",
       "APeelySmoothie",
       "A_Juke9",
       "Abaddon74",
       "AbraKadaver01",
       "ActivateFail",
       "Afuegonski71563",
       "AggroHamster59",
       "Agoraphone-8",
       "Agua_Cat",
       "Ahat4aMouse",
       "Aim Like Idaho",
       "AlbaThor300",
       "Albacore6",
       "AleXandre2k1",
       "AligatorPear",
       "AllTheCandy",
       "Allsmyles:D",
       "AlmaPura95",
       "AlpacaDaSorte",
       "AlphaPlayer34517",
       "Alternative74",
       "Alvaritooooh",
       "AlwaysOnTime38",
       "Amanda9938643",
       "Ambrosia0",
       "AmpleBlindspot",
       "AngelEye30",
       "Angrification",
       "AngryDuck51",
       "AngryMiau",
       "AngryRabbit9",
       "AngryRoommate10",
       "Anonymutt",
       "AplastaBravas",
       "Aplastafritas",
       "Apricot661",
       "Archibard11",
       "Arclite28",
       "ArcticAndroid",
       "Arczi80408",
       "Argathus",
       "Armstrong78",
       "Arrigoni347",
       "Asi_Portakal",
       "AtTheBeach321",
       "AthenaOrApollo",
       "Atomizer5",
       "AttackOLantern",
       "Avlry",
       "AyeBall23",
       "Ayıdoğan_19",
       "BLTZ_Edgadot",
       "BONES_GT4-42",
       "BabySeahorse81",
       "Back2Work61",
       "BadKahuna94",
       "Baethal",
       "Bag0Hammers",
       "BagelBoy82",
       "Bagigio_99",
       "BaguettePower75",
       "BaguetteWarrior11485",
       "Balefire81",
       "BananaPastrami",
       "Banandana82",
       "Barktooth81",
       "Bartolone811",
       "BatTacos",
       "BattleHammer7",
       "BeRooted",
       "BearPuns55",
       "BeeHive7",
       "Beebitme",
       "BeefSupreme35",
       "MarvelcoDev",
       "Zinx", // :heart:
       "Forty",
       "GD-TJ", // :heart:
       "MagmaDev",
       "ObsessedTech", // :heart:
       "Pongo_x64",
       "Akadi",
       "Therevisitor",
       "Hagi",
       "Hex",
       "ApfelTeeSaft",
       "Milxnor",
       "Max",
       "NotTacs", // :heart:
       "raax",
       "Skies", // :heart:
       "El pickato", // :heart:
       "timmiedevelops", // :heart:
       "waslyl",
       "Loigi", // :heart:
       "Zetax", // :heart:
       "dimiraku", // :heart:
};